services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/based-agent-test:latest@sha256:1e6973bcac4561d4f235da44b156eb6a43f642d2488342bdf298b901bddeee70
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
