services:
    web:
        platform: linux/amd64 # Explicitly set for TDX
        image: pivortex/based-agent-test:latest@sha256:11f3f1850e52ac83cc99cec4d27882fe3dd1a752a82279310d43ced865095df7
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
